name: Run tests
on:  
  push:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test (jest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test